spring:
    datasource:
        url: jdbc:mysql://localhost:3306/acquirence_ebdb
        username: root
        password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

    output:
        ansi:
            enabled: always
server:
  port: 8082
    
        